### ISSUE TITLE
'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by artchsh** [artchsh/instagram-bot#1]
`Traceback (most recent call last):
  File "D:\projects\Github\instagram-bot\main.py", line 221, in <module>
    init()
  File "D:\projects\Github\instagram-bot\main.py", line 47, in init
    menu()
  File "D:\projects\Github\instagram-bot\main.py", line 58, in menu
    activateBot()
  File "D:\projects\Github\instagram-bot\main.py", line 92, in activateBot
    sendAnswer(inboxFormatted1)
  File "D:\projects\Github\instagram-bot\main.py", line 141, in sendAnswer
    args = msg_text.split()
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'`

**Comment by sidd6p** [comment]
Hey, I can fix this bug.
Would you like to assign this to me

**Comment by artchsh** [comment]
Sorrry for long answer. Sure @sidd6p
